TrailerWeb/Controllers/dbTrailersController.cs
using System.Data.Entity;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using TrailerWeb.Permisos;
namespace TrailerWeb.Controllers
{
    //[ValidarSesion]

    public class dbTrailersController : Controller
    {
        private Db_MOVIEEntities db = new Db_MOVIEEntities();

        // GET: dbTrailers
        public ActionResult Index()
        {
            return View(db.dbTrailers.ToList());
        }


        // GET: dbTrailers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            dbTrailers dbTrailers = db.dbTrailers.Find(id);
            if (dbTrailers == null)
            {
                return HttpNotFound();
            }
            return View(dbTrailers);
        }

        // GET: dbTrailers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: dbTrailers/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_Trailer,Titulo,Director,Sipnosis,Reparto,Duracion,Fecha,Trailer,img_logo")] dbTrailers dbTrailers)
        {
            HttpPostedFileBase FileBase = Request.Files[0]; 

            if(FileBase.ContentLength == 0)
            {
                ModelState.AddModelError("img_logo", "Es necesario seleccionar una imagen");
            }
            else
            {
                if (FileBase.FileName.EndsWith(".jpg"))
                {
                    WebImage image = new WebImage(FileBase.InputStream);

                    dbTrailers.img_logo = image.GetBytes();
                }
                else
                {
                    ModelState.AddModelError("img_logo", "El sistema solo acepta imagenes .JPG");
                   
                }

               
            }


            //HttpFileCollectionBase collectionBase = Request.Files;

            

            if (ModelState.IsValid)
            {
                db.dbTrailers.Add(dbTrailers);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(dbTrailers);
        }

        // GET: dbTrailers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            dbTrailers dbTrailers = db.dbTrailers.Find(id);
            if (dbTrailers == null)
            {
                return HttpNotFound();
            }
            return View(dbTrailers);
        }

        // POST: dbTrailers/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_Trailer,Titulo,Director,Sipnosis,Reparto,Duracion,Fecha,Trailer,img_logo")] dbTrailers dbTrailers)
        {
            //byte[] imagenActual = null;

            dbTrailers   _Trailers = new dbTrailers (); 

            HttpPostedFileBase FileBase = Request.Files[0];
            if (FileBase.ContentLength == 0)
            {
                _Trailers = db.dbTrailers.Find(dbTrailers.ID_Trailer);
                dbTrailers.img_logo = _Trailers.img_logo;
            }
            else
            {

                if (FileBase.FileName.EndsWith(".jpg"))
                {
                    WebImage image = new WebImage(FileBase.InputStream);

                    dbTrailers.img_logo = image.GetBytes();
                }
                else
                {
                    ModelState.AddModelError("img_logo", "El sistema solo acepta imagenes .JPG");
                }

            }

            if (ModelState.IsValid)
            {
                db.Entry(_Trailers).State = EntityState.Detached;
                db.Entry(dbTrailers).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(dbTrailers);
        }

        // GET: dbTrailers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            dbTrailers dbTrailers = db.dbTrailers.Find(id);
            if (dbTrailers == null)
            {
                return HttpNotFound();
            }
            return View(dbTrailers);
        }

        // POST: dbTrailers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            dbTrailers dbTrailers = db.dbTrailers.Find(id);
            db.dbTrailers.Remove(dbTrailers);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult getImage(int id)
        {
            dbTrailers trailer = db.dbTrailers.Find(id);
            byte[] byteImage = trailer.img_logo;

            MemoryStream memoryStream = new MemoryStream(byteImage);
            Image img = Image.FromStream(memoryStream);

            memoryStream = new MemoryStream();

            img.Save(memoryStream, ImageFormat.Jpeg);
            memoryStream.Position = 0;      

            return File(memoryStream,"image/jpg");
        }

    }
}

TrailerWeb/Views/dbTrailers/Create.cshtml
@model TrailerWeb.dbTrailers

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    @*<link rel="stylesheet" href="~/Content/css/form.css" asp-append-version="true" />*@
    <title>Create</title>
</head>

<body>
    @using (Html.BeginForm("Create", "dbTrailers", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>dbTrailers</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Director, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Director, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Director, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Sipnosis, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @*<textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>*@
                    @Html.EditorFor(model => model.Sipnosis, new { htmlAttributes = new { @class = "form-control"  }  })
        @*<textarea  class="form-control" name="Sipnosis" id="" cols="30" rows="10" placeholder="Sipnosis" required></textarea>*@
                    @Html.ValidationMessageFor(model => model.Sipnosis,  "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Reparto, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Reparto, new { htmlAttributes = new { @class = "form-control" } })
                    @*<textarea class="form-control" name="Reparto" id="" cols="20" rows="10" placeholder="Reparto" required></textarea>*@
                    @Html.ValidationMessageFor(model => model.Reparto, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Duracion, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Duracion, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Duracion, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Fecha, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Fecha, new { htmlAttributes = new { @class = "form-control" } })
                    @*<input type="date" id="start" name="trip-start" value="2022-04-21">*@                           
                    @Html.ValidationMessageFor(model => model.Fecha, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Trailer, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Trailer, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Trailer, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.img_logo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @*@Html.EditorFor(model => model.img_logo, new { htmlAttributes = new { @class = "form-control" } })*@
                    <input type="file" name="imgload"/>
                    @Html.ValidationMessageFor(model => model.img_logo, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div class="btn-link">
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

TrailerWeb/Views/dbTrailers/Delete.cshtml
@model TrailerWeb.dbTrailers

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="~/Content/css/form.css" asp-append-version="true" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>dbTrailers</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Titulo)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Titulo)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Director)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Director)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Sipnosis)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Sipnosis)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Reparto)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Reparto)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Duracion)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Duracion)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Fecha)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Fecha)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Trailer)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Trailer)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.img_logo)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.img_logo)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

TrailerWeb/Views/dbTrailers/Details.cshtml
@model TrailerWeb.dbTrailers

@{
    Layout = null;
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="~/Content/css/crudStyle.css" asp-append-version="true" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>dbTrailers</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Titulo)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Titulo)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Director)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Director)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Sipnosis)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Sipnosis)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Reparto)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Reparto)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Duracion)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Duracion)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Fecha)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Fecha)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Trailer)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Trailer)
            </dd>
    
            @*<dt>
                @Html.DisplayNameFor(model => model.img_logo)
            </dt>*@
    
            @*<dd>
                @Html.DisplayFor(model => model.img_logo)
            </dd>*@
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.ID_Trailer }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

TrailerWeb/Views/dbTrailers/Edit.cshtml
@model TrailerWeb.dbTrailers

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="~/Content/css/CRUD.css" asp-append-version="true" />
    <title>Edit</title>
</head>
<body>

    @using (Html.BeginForm("Edit", "dbTrailers", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>dbTrailers</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ID_Trailer)

            <div class="form-group">
                @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Director, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Director, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Director, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Sipnosis, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Sipnosis, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Sipnosis, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Reparto, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Reparto, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Reparto, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Duracion, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Duracion, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Duracion, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Fecha, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Fecha, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Fecha, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Trailer, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Trailer, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Trailer, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.img_logo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @*@Html.EditorFor(model => model.img_logo, new { htmlAttributes = new { @class = "form-control" } })*@
                    <img width="100px"  src="@Url.Action("getImage", "dbTrailers", new {id=Model.ID_Trailer})" alt="Alternate Text" />
                    <input type="file" name="imgload" />
                    @Html.ValidationMessageFor(model => model.img_logo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

TrailerWeb/Views/dbTrailers/Index.cshtml
@model IEnumerable<TrailerWeb.dbTrailers>

@{
    Layout = null;
}


<!DOCTYPE html>

<html>
<head>

    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <script src="https://kit.fontawesome.com/f832396757.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/Content/css/crudStyle.css" asp-append-version="true" />
</head>
<body>
    <div class="container-index">
        <div class="container">
            <p>
                <a href="#"><i class="fa-solid fa-square-plus"></i> @Html.ActionLink("Create New", "Create")</a>
                 
            </p>
            <table class="table">
                <tr>
                    <th>

                        @Html.DisplayNameFor(model => model.Titulo)
                       
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Director)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Sipnosis)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Reparto)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Duracion)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Fecha)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Trailer)
                    </th>
                    @*<th>
                        @Html.DisplayNameFor(model => model.img_logo)
                    </th>*@
                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Titulo)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Director)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Sipnosis)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Reparto)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Duracion)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Fecha)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Trailer)
                        </td>
                        @*<td>
                            @Html.DisplayFor(modelItem => item.img_logo)
                        </td>*@
                    <td>
                        
                        <a href="#"><i class="fa-solid fa-file-pen"></i> @Html.ActionLink("Edit", "Edit", new { id = item.ID_Trailer }) |</a>
                        <a href="#"><i class="fa-regular fa-pen-to-square"></i> @Html.ActionLink("Details", "Details", new { id = item.ID_Trailer }) |</a> 
                        <a href="#"><i class="fa-regular fa-trash-can"></i>  @Html.ActionLink("Delete", "Delete", new { id = item.ID_Trailer })</a>
                        
                    </td>
                    </tr>
                }

            </table>
        </div>
    </div>
</body>
</html>